image: centos

before_script:
 - echo "Starting Gitlab-CI script"
 - docker info

stages:
 - test
 - deploy

build_job:
  stage: test
  script:
  - cd /builds/william/flaskrcloud ; make all ; make fulltest
  - curl -v localhost:5000

deploy_job:
  stage: deploy
  script:
  - echo "Nothing here... future"
  
