image: centos

before_script:
 - echo "Starting Gitlab-CI script"
 - docker info

stages:
 - buildcontainer
 - deploy

buildcontainer_job:
  stage: buildcontainer
  tags:
  - baremetal
  - docker
  script:
#  - make all # Disabled to speed tests
  - make fulltest
  - echo "Sleeping to allow containers to become available" ; sleep 5
  - curl localhost:5000
  - make fullclean
  - docker tag -f flaskrcloud registry.snappyvault.com:5000/flaskrcloud
  - docker push registry.snappyvault.com:5000/flaskrcloud

deploy_job:
  stage: deploy
  tags:
  - baremetal
  - docker
  - production
  script:
  - echo "Deploying conainers..."
  - echo "Note: we could use a bash script to determine if container already exist to do proper cleaning"
  - docker run -d -p 5984:5984 -v /opt/couchdb:rw  --name couchdb klaemo/couchdb
  - docker run -d -P --name flaskrcloud registry.snappyvault.com:5000/flaskrcloud
 
